language: python
python:
  - "2.6"
before_install: "sudo apt-get install python-dev libevent-dev"
install:
  - pip install flake8
  - python setup.py install
script:
- python setup.py test
- flake8 .
notifications:
  email:
    - tarun.bhardwaj@openlabs.co.in
    - ci-notify@openlabs.co.in
